version: '3'

services:
  app:
    container_name: app-development
    build:
      context: . # If your Dockerfile is not at the same level change the path here (./docker)
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  postgres-db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
